package personalbudgetingapp;

public enum CategoryofIncome {
	WAGE, SALARY, COMISSION, INTERESTS, DIVIDENDS, SALE, RENTAL_INCOME, GIFTS, DUES, GRANTS, LENDING, RENTING, GAMBLING, POCKET_MONEY, ALLOWANCE, GOVERMENT_SUPPORT, 
	REFUNDS, ROYALTIES, SAVINGS, OTHER;
	
	

}
